openapi: 3.0.0
info:
  title: DanEvents API
  description: API documentation for the DanEvents event booking platform
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /api/events:
    get:
      summary: Get all events
      responses:
        '200':
          description: A list of events
  /api/events/{id}:
    get:
      summary: Get event by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Event found
        '404':
          description: Event not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
